### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by oliveirajne** [oliveirajne/crud-node#1]
- [x] tratar coleta de senha de forma segura
- [x] escrever documentação detalhada 
- [x] trocar credenciais do knexfile.js
